// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Button() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`margin:10px 0px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`padding:12px 24px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-size:20px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background:#26eb9f;`)
	templ_7745c5c3_CSSBuilder.WriteString(`opacity:0.8;`)
	templ_7745c5c3_CSSBuilder.WriteString(`color:#131315;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`border-radius:10px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`box-shadow:none;`)
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:'GWENT';`)
	templ_7745c5c3_CSSBuilder.WriteString(`cursor:pointer;`)
	templ_7745c5c3_CSSBuilder.WriteString(`transition:opacity 0.3s ease;`)
	templ_7745c5c3_CSSID := templ.CSSID(`Button`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var _ = templruntime.GeneratedTemplate
